services:
  kali:
    build: .
    container_name: kali
    user: root
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - "5901:5901"
      - "6901:6901"
    volumes:
      - ./data:/root/data
    environment:
      - DISPLAY=:1
      - VNC_PW=password
      - USER=root
    command: >
      /bin/bash -c "
      service postgresql start &&
      su -c 'vncserver :1 -geometry 1600x900 -depth 24' root &&
      websockify --web=/usr/share/novnc/ --wrap-mode=ignore 6901 localhost:5901
      "
